# Generated by Django 4.2.5 on 2025-09-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0002_column_task_taskattachment_taskcomment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='color',
            field=models.CharField(default='#e6f3ff', help_text='Cor em formato hex (#ffffff)', max_length=7),
        ),
    ]
