# Generated by Django 4.2.5 on 2025-11-05 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatattachment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='chatattachment',
            name='file_name',
            field=models.CharField(blank=True, help_text='Nome do arquivo', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chatattachment',
            name='file_type',
            field=models.CharField(blank=True, help_text='Tipo do arquivo (ex: image/png)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='chatattachment',
            name='file_url',
            field=models.URLField(blank=True, help_text='URL do arquivo', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='chatattachment',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
